modLoader = "javafml" #mandatory
loaderVersion = "[1,)" #mandatory
license = "${license_url}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${mod_source}/issues" #optional
sourcesURL = "${mod_source}" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "${display_url}" #optional (displayed in the mod UI)
logoFile = "logo.png" #optional
credits = "${credits}" #optional
authors = "${author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)

# https://docs.neoforged.net/docs/gettingstarted/modfiles#dependency-configurations
[dependencies]
"${mod_id}" = [
  { modId = "neoforge", type = "required", versionRange = "${neoforge_version_range}", ordering = "NONE", side = "BOTH", mc-publish = { ignore = true } },
  { modId = "minecraft", type = "required", versionRange = "${minecraft_version_range}", ordering = "NONE", side = "BOTH" },
  { modId = "resourcefulconfig", type = "required", versionRange = "[${resourceful_config_neoforge_version},)", ordering = "NONE", side = "BOTH" }
]

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
[features.${ mod_id }]
#openGLVersion="[3.2,)"
javaVersion = "[${java_version},)"

[mc-publish]
curseforge = "${curseforge_id}"
modrinth = "${modrinth_id}"
loaders = ["neoforge"]

dependencies = [
  "resourcefulconfig(required){modrinth:M1953qlQ}{curseforge:714059}"
]
